#!/bin/bash

if [ ! -d ~/power ]; then
  mkdir -p ~/power
fi

sshfs ada10sny@power.cs.lth.se: ~/power -o IdentityFile=~/.ssh/ssh-key_rsa
ssh power "cd factorial_par_cpp; git pull origin master; ./tt a b c"
